- name: Add repository
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | bash -

- name: Install nodejs
  yum: name=nodejs state=present

- name: Add repository yarn
  shell: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo

- name: Install yarn
  yum: name=yarn state=present
