- name: delete mariadb
  yum: name=mariadb-libs state=absent

- name: delete mysql lib folder
  file:
    path: /var/lib/mysql/
    state: absent

- name: install yum repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm
    state: present

# - name: get mysql package
#   shell: wget https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm

# - name: upgrade package
#   shell: rpm -Uvh /home/vagrant/mysql80-community-release-el7-2.noarch.rpm

- name: disable mysql80-community
  command: yum-config-manager --disable mysql80-community

- name: enable mysql57-community
  command: yum-config-manager --enable mysql57-community

# - name: install mysql lib
#   yum:
#     name=mysql-community-common
#     state=present

- name: install community server
  yum:
    name=mysql-community-server
    state=present

# - name: install mysql lib
#   yum:
#     name:
#       - mysql-community-server
#       - mysql-community-client
#       - mysql-community-common
#       - mysql-community-libs
#       - mysql-community-libs-compat
#     state: present

- name: install mysql-python library
  yum:
    name: MySQL-python
    state: present

# - name: put my.cnf
#   template:
#     src: my.cnf.j2
#     dest: /etc/my.cnf

- name: start mysql
  systemd:
    name: mysqld
    state: started
    daemon_reload: yes
    enabled: yes

- name: get temporary password
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: mysql_default_password

- name: root password changed
  mysql_user: name=root password=grizzly1! host=localhost
