- name: delete mariadb
  yum: name=mariadb-libs state=absent

# - name: delete mysql
#   file: path=/var/lib/mysql/ state=absent

- name: add mysql yum repository
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm
    state: present

- name: install mysql library
  yum:
    name: MySQL-python
    state: present

- name: disable mysql80-community
  command: yum-config-manager --disable mysql80-community

- name: enable mysql57-community
  command: yum-config-manager --enable mysql57-community

- name: install mysql
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-2.noarch.rpm

- name: start mysql
  service: name=mysqld enabled=yes state=started

- name: root password changed
  mysql_user: name=root password=grizzly1! host=localhost
