AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/initializers/assets.rb'
    - 'node_modules/node-sass/src/libsass/extconf.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40
