require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/initializers/assets.rb'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Guardfile'

Metrics/MethodLength:
  Max: 40

Metrics/LineLength:
  Max: 130

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MixinUsage:
  Include:
    - 'app/**/*.rb'

RSpec/ContextWording:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Enabled: false
