- name: initial setting confirmation
  stat:
    path: /home/grizzly/.rbenv
  register: rbenv_stat

- name: git clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/grizzly/.rbenv
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: compile rbenv
  shell: cd ~/.rbenv && src/configure && make -C src
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: setting bash_profile
  blockinfile:
    dest: /home/grizzly/.bash_profile
    owner: grizzly
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: make plugin directory
  file:
    path: /home/grizzly/.rbenv/plugins
    owner: grizzly
    state: directory
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: install plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/grizzly/.rbenv/plugins/ruby-build
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: install library
  yum:
    name:
      - openssl-devel
      - readline-devel
      - zlib-devel
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: rbenv install
  shell: bash -lc "rbenv install 2.5.1"
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: setting ruby version
  shell: bash -lc "rbenv shell 2.5.1"
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: rbenv global
  shell: bash -lc "rbenv global 2.5.1"
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: install bundler
  gem:
    name: bundler
    version: 1.3.0
    user_install: False
    executable: /home/grizzly/.rbenv/shims/gem
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode

- name: install rails
  gem:
    name: rails
    version: 5.2.2
    user_install: False
    executable: /home/grizzly/.rbenv/shims/gem
  become_user: grizzly
  when: rbenv_stat.stat.isdir is not defined and not ansible_check_mode
